ENV_MASTER = "MASTER"
SPARK_CONFIG_MASTER = "spark.master"
DEFAULT_MASTER = "local[*]"

ENV_MAX_MEMORY = "MAX_MEMORY"
SPARK_CONFIG_MEMORY = "spark.executor.memory"
DEFAULT_MAX_MEMORY = "4g"

ENV_DATA_PATH = "DATA_PATH"
DEFAULT_DATA_PATH = "/data/*.csv"